# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test

# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq

variables:
  # MAVEN_CLI_OPTS: "-f ./app/collector/pom.xml"
  # MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PYTHON_SCRIPTS: ./app/api/
  JAVASCRIPT_SCRIPTS: ./app/gui/
  SHELL_SCRIPTS: ./bin/

git-secrets:
  stage: test
  image: debian:bookworm
  script:
  - apt-get install wget unzip make git -qy
  - wget 'https://github.com/awslabs/git-secrets/archive/refs/tags/1.3.0.zip'
  - unzip 1.3.0.zip && rm 1.3.0.zip
  - cd git-secrets-1.3.0 && make install
  - git secrets --scan -r ./

# java-mvn:
#   stage: test
#   image: maven:latest
#   script:
#   - mvn $MAVEN_CLI_OPTS clean compile test

python-bandit:
  stage: test
  image: debian:bookworm
  script:
  - apt-get install python3-bandit -qy
  - bandit --version
  - bandit -c .bandit.yml -r $PYTHON_SCRIPTS

# shellcheck:
#   stage: test
#   image: debian:testing
#   script:
#   - apt-get install shellcheck -qy
#   - shellcheck --version
#   - shellcheck $SHELL_SCRIPTS
